This is makeindex, version 2.15 [TeX Live 2011] (kpathsea + Thai support).
Scanning style file ./Moodle + Potenziamento soluzioni Wiki e DMS.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Moodle + Potenziamento soluzioni Wiki e DMS.acn....done (3 entries accepted, 0 rejected).
Sorting entries....done (4 comparisons).
Generating output file Moodle + Potenziamento soluzioni Wiki e DMS.acr....done (9 lines written, 0 warnings).
Output written in Moodle + Potenziamento soluzioni Wiki e DMS.acr.
Transcript written in Moodle + Potenziamento soluzioni Wiki e DMS.alg.
